# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1piT_FpcC1nc3lbiliTQqSbYBJ0yv8Re5
"""

cafe_gu = pd.read_csv("cafe_gu.csv")
density_area = pd.read_csv("density_area.csv")
final_df = pd.read_csv("final_df.csv")